name = "iot-home-wybran"
main = "src/worker.ts"
compatibility_date = "2023-06-14"

[[d1_databases]]
binding = "DB"
database_name = "iot-home-wybran"
database_id = "26438823-baa8-4eac-95db-f7424d6d4158"