import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Line } from 'react-chartjs-2';
import { useData } from '@/features/useData'
import Head from 'next/head'
import { TempIndoor } from '@/features/useData/types';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

export default function Home() {

  const { tempIndoorData } = useData()

  const timestampToTime = (unixTime: number) => {
    const date = new Date(unixTime * 1000)
    const hours = date.getHours()
    const minutes = "0" + date.getMinutes()

    return hours + ':' + minutes.substr(-2)
  }

  const labels = tempIndoorData && tempIndoorData.map((item) => timestampToTime(item.TimeStamp))

 const data = {
    labels,
    datasets: [
      {
        label: 'Temperatura',
        data: labels.map((item, index) => tempIndoorData && tempIndoorData[index].Temperature),
        borderColor: 'rgb(255, 99, 132)',
        backgroundColor: 'rgba(255, 99, 132, 0.5)',
      },
      {
        label: 'Wilgotność',
        data: labels.map((item, index) => tempIndoorData && tempIndoorData[index].Humidity),
        borderColor: 'rgb(54, 162, 235)',
        backgroundColor: 'rgba(54, 162, 235, 0.5)',
      },
    ],
  };
  
 const options = {
    responsive: true,
    plugins: {
      legend: {
        position: 'top' as const,
      },
      title: {
        display: true,
        text: 'Chart.js Line Chart',
      },
    },
  };
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        {tempIndoorData && <Line options={options} data={data} /> }

      </main>
    </>
  )
}
