CREATE TABLE IF NOT EXISTS TempIndoor (Id INTEGER PRIMARY KEY, Temperature REAL, Humidity REAL, TimeStamp REAL);
CREATE TABLE IF NOT EXISTS TempOutdoor (Id INTEGER PRIMARY KEY, Temperature REAL, TimeStamp REAL);
CREATE TABLE IF NOT EXISTS Waterflow (Id INTEGER PRIMARY KEY, Count REAL, Total REAL, Time REAL, TimeStamp REAL);